WITH CTE AS(
SELECT 
STARTED_AT,
-- TO_TIMESTAMP(STARTED_AT) as STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) as DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
{{ get_day_type('STARTED_AT') }}AS DAY_TYPE,
{{ get_seaon('STARTED_AT') }}  AS STATION_OF_YEAR,
{{function1('STARTED_AT')}}

FROM
{{ source('demo', 'bike') }}
where STARTED_AT != 'started_at'

)

SELECT * FROM CTE