WITH CTE AS(
SELECT 
TO_TIMESTAMP(REPLACE(STARTED_AT,'"','')) AS STARTED_AT,
-- TO_TIMESTAMP(STARTED_AT) as STARTED_AT,
DATE(TO_TIMESTAMP(REPLACE(STARTED_AT,'"',''))) as DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(REPLACE(STARTED_AT,'"',''))) AS HOUR_STARTED_AT,
{{ get_day_type('STARTED_AT') }}AS DAY_TYPE,
{{ get_season('STARTED_AT') }}  AS STATION_OF_YEAR,
{{function1('STARTED_AT')}}

FROM
{{ ref('stage_bike') }}
where STARTED_AT != 'started_at' and STARTED_AT != 'starttime'

)

SELECT * FROM CTE