WITH TRIPS AS (
select 

RIDE_ID,
RIDEABLE_TYPE,
TO_TIMESTAMP(STARTED_AT) AS TRIP_DATE,
start_statio_id AS START_STATION_ID,
END_STATION_ID,
MEMBER_CSUAL,
TIMESTAMPDIFF(SECOND,TO_TIMESTAMP(STARTED_AT),TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS,

from
{{ source('demo', 'bike') }}
where RIDE_ID <> 'ride_id'
limit 10
)

select * from TRIPS
