WITH TRIPS AS (
select 

RIDE_ID,

-- RIDEABLE_TYPE,
TO_TIMESTAMP(REPLACE(STARTED_AT,'"','')) AS TRIP_DATE,
start_statio_id AS START_STATION_ID,
END_STATION_ID,
MEMBER_CSUAL,
TIMESTAMPDIFF(SECOND,TO_TIMESTAMP(REPLACE(STARTED_AT,'"','')),TO_TIMESTAMP(REPLACE(ENDED_AT,'"',''))) AS TRIP_DURATION_SECONDS,

from
{{ ref('stage_bike') }}
where RIDE_ID <> 'ride_id'
)

select * from TRIPS
